### ISSUE TITLE
Continual: "Save data not found.  Select PS4 to skip this step, and disable PC specific features."

### ISSUE THREAD

**Issue by ryanniehaus** [jaszhix/NoMansConnect#100]
Problem Description:
I continually get the error message: "Save data not found.  Select PS4 to skip this step, and disable PC specific features."  If I pick PC and specify my save location, the app restarts and the same prompt comes up again.
NMC.log contains:

> 1535420900977:    Initializing No Man's Connect 1.5.3 
1535420902321:    Failed to locate NMS install: path doesn't exist. 
1535420906102:    SAVE DIRECTORY:  C:\Users\goose\AppData\Roaming\HelloGames\NMS\st_76561197980314510 
1535420906888:    Unable to retrieve NMS save file:  Cannot read property 'dataId' of null
TypeError: Cannot read property 'dataId' of null
    at _state2.default.ps4User._location (file:///C:/Users/goose/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2038895)
    at findIndex (file:///C:/Users/goose/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:1937720)
    at then.saveData (file:///C:/Users/goose/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2038841)
    at run (file:///C:/Users/goose/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2332594)
    at file:///C:/Users/goose/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2332869
    at flush (file:///C:/Users/goose/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2240392)
    at process._tickCallback (internal/process/next_tick.js:61:11)

Windows version:
Windows 10 Version 1804 (OS Build 17134.228)

NMC version:
1.5.3

- Absolute path to your storage_x.hg files:
C:\Users\goose\AppData\Roaming\HelloGames\NMS\st_76561197980314510
This path contains save.hg, save2.hg, save3.hg, save4.hg, storage.hg, storage2.hg, storage3.hg, mf_save*.hg, mf_storage.hg.
My main save is save.hg.

- Absolute path to your NMS install directory:
C:\Program Files (x86)\Steam\steamapps\common\No Man's Sky
Contains these subfolders:
_CommonRedist, Binaries, GAMEDATA, steam_shader_cache

NMC.log and settings.json files in [NoMansConnect_debug.zip](https://github.com/jaszhix/NoMansConnect/files/2326182/NoMansConnect_debug.zip)

- How can this bug be reproduced? -> Happens constantly for me.

It had been working fine after the NEXT update, but a recent update of No Man's Connect started this problem for me.

**Comment by jaszhix** [comment]
Does it still occur if you delete entire contents of C:\Users\goose\AppData\Roaming\NoMansConnect? 1.5.0 changed the model schema for locations, and when you upgrade its supposed to delete the old cache, but recently been finding out that's not always working.

**Comment by Eeveevolve** [comment]
Same issue, and I have tried deleting entire contents of Roaming\NoMansConnect

>
1535472598336:    Initializing No Man's Connect 1.5.3 
1535472598389:    Initializing No Man's Connect 1.5.3 
1535472600734:    SAVE DIRECTORY:  C:\Users\Eevee\AppData\Roaming\HelloGames\NMS 
1535472600906:    C:\Users\Eevee\AppData\Roaming\HelloGames\NMS,  
1535472600874:    Unable to retrieve NMS save file:  Cannot read property 'UniverseAddress' of undefined
TypeError: Cannot read property 'UniverseAddress' of undefined
    at then.saveData (file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2038779)
    at run (file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2332594)
    at file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2332869
    at flush (file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2240392)
    at process._tickCallback (internal/process/next_tick.js:61:11)

1535472610787:    Initializing No Man's Connect 1.5.3 
1535472612747:    SAVE DIRECTORY:  C:\Users\Eevee\AppData\Roaming\HelloGames\NMS\st_76561198001457057 
1535472612883:    Unable to retrieve NMS save file:  Cannot read property 'UniverseAddress' of undefined
TypeError: Cannot read property 'UniverseAddress' of undefined
    at then.saveData (file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2038779)
    at run (file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2332594)
    at file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2332869
    at flush (file:///C:/Users/Eevee/AppData/Local/Programs/NoMansConnect/resources/app.asar/dist/bundle.js:1:2240392)
    at process._tickCallback (internal/process/next_tick.js:61:11)

1535472612915:    C:\Users\Eevee\AppData\Roaming\HelloGames\NMS\st_76561198001457057,  
>

**Comment by ryanniehaus** [comment]
@jaszhix 
Deleting C:\Users\goose\AppData\Roaming\NoMansConnect did fix it for me.
I did remember reading that in one of the previous release notes, but completely forgot to try.
Thanks!

I'll let you decide whether you want to keep this open for @Eeveevolve 's issue

**Comment by ViktorKrugar** [comment]
I deleted my \AppData\Roaming\NoMansConnect. But it did not correct the problem.

**Comment by jaszhix** [comment]
@ryanniehaus Thanks for the confirmation.

@Eeveevolve @ViktorKrugar Would you be able to provide NMC.log and settings.json? I would prefer that one to be handled in a new issue since the symptoms and stack trace are different.

**Comment by jaszhix** [comment]
@Eeveevolve @ViktorKrugar Hi, I reproduced this issue, they completely changed the save file formatting for the experimental version - will try to fix it soon. Opened #101 for this.
